### ISSUE TITLE
[BUG] Posting Event in The Forums generate 514 or 504 Error

### ISSUE THREAD

**Issue by kmoberg** [VATUSA/forums#2] opened 2021-07-27 13:16 UTC
### Contact Details

atm@nyartcc.org

### What happened?

Posting a new event in the forums, or creating a new thread in the events forum posts the thread, but times out either with a 504 or 514 error. 

### How can it be reproduced?

Post a new thread to the events forum, or create a new event under calendar.

### What browsers are you seeing the problem on?

Firefox, Safari

### Screenshots

http://kmoberg.io/GRnNcv

**Comment by dhawton** [comment] 2021-07-27 22:00
Not a bug.

**Comment by kmoberg** [comment] 2021-07-27 22:02
> Not a bug.

Super useful feedback! Thank you! So we can just expect the website to generate these errors?

**Comment by dhawton** [comment] 2021-07-27 22:11
@kmoberg Software bugs are not networking issues. https://en.wikipedia.org/wiki/Software_bug We will investigate the network issue, however, it is not a bug.

**Comment by kmoberg** [comment] 2021-07-27 22:12
So please... Do explain to me how I can report this issue, since we no longer have a centralized way to do it, and this sure as hell is not a FEATURE SUGGESTION.

**Comment by asherrobinson** [comment] 2021-07-27 22:49
> dhawton closed this 40 minutes ago
gotta keep those issue resolution stats pristine. close it out! solve it later if you feel like it i guess ¯\_(ツ)_/¯ 

in all seriousness, if the app is otherwise functional, and only times out when making a specific type of request, and the issue is recreatable when making the same type of request, that would suggest that there is likely a problem with that particular route/flow/module/etc....but regardless, blaming "the network" and closing the ticket feels pretty dismissive when a user is just trying to make you aware of a problem. 

but at least you patronizingly linked him to a wikipedia page, so alls well and you win, right?

**Comment by dhawton** [comment] 2021-07-27 22:53
@asherrobinson A Cloudflare 504 error is the very definition of a network issue. https://support.cloudflare.com/hc/en-us/articles/115003011431-Troubleshooting-Cloudflare-5XX-errors#502504error An issue with a particular route/flow/module/etc. does not generate a 504 error.

**Comment by bnahin** [comment] 2021-07-28 01:36
Reopening. This issue is also occurring in Moodle, perhaps as a result of the Docker web server configuration. We will look into it.

**Comment by bnahin** [comment] 2021-08-07 23:34
This issue is not completely resolved yet and we are continuing to troubleshoot.

**Comment by dhawton** [comment] 2021-08-08 00:16
> This issue is not completely resolved yet and we are continuing to troubleshoot.

Caused by mail server settings. Since the forums no longer have the ability to send email, but SMF doesnt have a way to disable, the attempts are still being made and failing, but they take so long to fail that the php processes are being timed out. We need to provide the forums with a way to send emails, even if they don't go anywhere, or we need to modify SMF to not actually send emails.

**Comment by bnahin** [comment] 2021-08-15 04:37
Mail settings have been fixed and outgoing mail is now successful.

**Closed as completed by bnahin** 2021-08-15 04:37 UTC
Labels: misc. issue
