### ISSUE TITLE
[BUG] Database error accessing EVENTS

### ISSUE THREAD

**Issue by MacMinnS** [VATUSA/forums#5] opened 2021-07-28 01:27 UTC
### Contact Details

skylar.hutter@zabartcc.org

### What happened?

Any link to the calendar or events forum or events posts are giving a "Database Error" in the header 

https://forums.vatusa.net/index.php?board=8.0

### How can it be reproduced?

https://forums.vatusa.net/index.php?board=8.0

### What browsers are you seeing the problem on?

Firefox

**Comment by bnahin** [comment] 2021-07-28 01:28
Duplicate of #3.

**Closed as completed by bnahin** 2021-07-28 01:28 UTC
Labels: bug
